{
  countries: {
    AU: "Australia";
    BR: "Brazil";
    CA: "Canada";
    DK: "Denmark";
    EG: "Egypt";
    FI: "Finland";
    FR: "France";
    DE: "Germany";
    IN: "India";
    IT: "Italy";
    MY: "Malaysia";
    MX: "Mexico";
    NZ: "New Zealand";
    NO: "Norway";
    PL: "Poland";
    QA: "Qatar";
    RO: "Romania";
    SA: "Saudi Arabia";
    SG: "Singapore";
    ZA: "South Africa";
    ES: "Spain";
    SE: "Sweden";
    TH: "Thailand";
    TR: "Turkey";
    AE: "United Arab Emirates";
    GB: "United Kingdom";
    US: "United States";
  }
  statesByCountry: {
    US: [
      ["", "Select"],
      ["AL", "Alabama"],
      ["AZ", "Arizona"],
      ["AR", "Arkansas"],
      ["CA", "California"],
      ["CO", "Colorado"],
      ["CT", "Connecticut"],
      ["DE", "Delaware"],
      ["DC", "District of Columbia"],
      ["FL", "Florida"],
      ["GA", "Georgia"],
      ["HI", "Hawaii"],
      ["ID", "Idaho"],
      ["IL", "Illinois"],
      ["IN", "Indiana"],
      ["IA", "Iowa"],
      ["KS", "Kansas"],
      ["KY", "Kentucky"],
      ["LA", "Louisiana"],
      ["ME", "Maine"],
      ["MD", "Maryland"],
      ["MA", "Massachusetts"],
      ["MI", "Michigan"],
      ["MN", "Minnesota"],
      ["MS", "Mississippi"],
      ["MO", "Missouri"],
      ["MT", "Montana"],
      ["NE", "Nebraska"],
      ["NV", "Nevada"],
      ["NH", "New Hampshire"],
      ["NJ", "New Jersey"],
      ["NM", "New Mexico"],
      ["NY", "New York"],
      ["NC", "North Carolina"],
      ["ND", "North Dakota"],
      ["OH", "Ohio"],
      ["OK", "Oklahoma"],
      ["OR", "Oregon"],
      ["PA", "Pennsylvania"],
      ["RI", "Rhode Island"],
      ["SC", "South Carolina"],
      ["SD", "South Dakota"],
      ["TN", "Tennessee"],
      ["TX", "Texas"],
      ["UT", "Utah"],
      ["VT", "Vermont"],
      ["VA", "Virginia"],
      ["WA", "Washington"],
      ["WV", "West Virginia"],
      ["WI", "Wisconsin"],
      ["WY", "Wyoming"],
    ];
    CA: [
      ["", "Select"],
      ["AB", "Alberta"],
      ["BC", "British Columbia"],
      ["MB", "Manitoba"],
      ["NB", "New Brunswick"],
      ["NL", "Newfoundland and Labrador"],
      ["NT", "Northwest Territories"],
      ["NS", "Nova Scotia"],
      ["NU", "Nunavut"],
      ["ON", "Ontario"],
      ["PE", "Prince Edward Island"],
      ["QC", "Quebec"],
      ["SK", "Saskatchewan"],
      ["YT", "Yukon"],
    ];
    AU: [
      ["", "Select"],
      ["ACT", "Australian Capital Territory"],
      ["NSW", "New South Wales"],
      ["NT", "Northern Territory"],
      ["QLD", "Queensland"],
      ["SA", "South Australia"],
      ["TAS", "Tasmania"],
      ["VIC", "Victoria"],
      ["WA", "Western Australia"],
    ];
    IT: [
      ["", "Select"],
      ["AG", "Agrigento"],
      ["AL", "Alessandria"],
      ["AN", "Ancona"],
      ["AO", "Aosta"],
      ["AR", "Arezzo"],
      ["AP", "Ascoli Piceno"],
      ["AT", "Asti"],
      ["AV", "Avellino"],
      ["BA", "Bari"],
      ["BT", "Barletta-Andria-Trani"],
      ["BL", "Belluno"],
      ["BN", "Benevento"],
      ["BI", "Biella"],
      ["BO", "Bolonia"],
      ["BZ", "Bolzano"],
      ["BS", "Brescia"],
      ["BR", "Brindisi"],
      ["BG", "Bérgamo"],
      ["CA", "Cagliari"],
      ["CL", "Caltanissetta"],
      ["CB", "Campobasso"],
      ["CE", "Caserta"],
      ["CT", "Catania"],
      ["CZ", "Catanzaro"],
      ["SU", "Cerdeña del Sur"],
      ["CH", "Chieti"],
      ["CO", "Como"],
      ["CS", "Cosenza"],
      ["CR", "Cremona"],
      ["KR", "Crotona"],
      ["CN", "Cuneo"],
      ["EN", "Enna"],
      ["FM", "Fermo"],
      ["FE", "Ferrara"],
      ["FI", "Florencia"],
      ["FG", "Foggia"],
      ["FC", "Forlì-Cesena"],
      ["FR", "Frosinone"],
      ["GO", "Gorizia"],
      ["GR", "Grosseto"],
      ["GE", "Génova"],
      ["IM", "Imperia"],
      ["IS", "Isernia"],
      ["AQ", "L'Aquila"],
      ["SP", "La Spezia"],
      ["LE", "Lecce"],
      ["LI", "Livorno"],
      ["LO", "Lodi"],
      ["LU", "Lucca"],
      ["MC", "Macerata"],
      ["MN", "Mantua"],
      ["MS", "Massa y Carrara"],
      ["MT", "Matera"],
      ["ME", "Mesina"],
      ["MI", "Milán"],
      ["MB", "Monza y Brianza"],
      ["MO", "Módena"],
      ["NO", "Novara"],
      ["NU", "Nuoro"],
      ["NA", "Nápoles"],
      ["OR", "Oristán"],
      ["PD", "Padua"],
      ["PA", "Palermo"],
      ["PR", "Parma"],
      ["PV", "Pavía"],
      ["PG", "Perusa"],
      ["PU", "Pesaro y Urbino"],
      ["PE", "Pescara"],
      ["PI", "Pisa"],
      ["PT", "Pistoia"],
      ["PC", "Plasencia"],
      ["PN", "Pordenone"],
      ["PZ", "Potenza"],
      ["PO", "Prato"],
      ["RG", "Ragusa"],
      ["RC", "Reggio Calabria"],
      ["RE", "Reggio Emilia"],
      ["RI", "Rieti"],
      ["RM", "Roma"],
      ["RO", "Rovigo"],
      ["RA", "Rávena"],
      ["RN", "Rímini"],
      ["SA", "Salerno"],
      ["SV", "Savona"],
      ["SI", "Siena"],
      ["SR", "Siracusa"],
      ["SO", "Sondrio"],
      ["SS", "Sácer"],
      ["TA", "Tarento"],
      ["TE", "Teramo"],
      ["TR", "Terni"],
      ["TP", "Trapani"],
      ["TN", "Trento"],
      ["TV", "Treviso"],
      ["TS", "Trieste"],
      ["TO", "Turín"],
      ["UD", "Udine"],
      ["VA", "Varese"],
      ["VE", "Venecia"],
      ["VB", "Verbano-Cusio-Ossola"],
      ["VC", "Vercelli"],
      ["VR", "Verona"],
      ["VV", "Vibo Valentia"],
      ["VI", "Vicenza"],
      ["VT", "Viterbo"],
    ];
    MX: [
      ["", "Select"],
      ["AGS", "Aguascalientes"],
      ["BC", "Baja California"],
      ["BCS", "Baja California Sur"],
      ["CAMP", "Campeche"],
      ["CHIS", "Chiapas"],
      ["CHIH", "Chihuahua"],
      ["COAH", "Coahuila"],
      ["COL", "Colima"],
      ["DGO", "Durango"],
      ["CDMX", "Federal District"],
      ["GTO", "Guanajuato"],
      ["GRO", "Guerrero"],
      ["HGO", "Hidalgo"],
      ["JAL", "Jalisco"],
      ["MICH", "Michoacán"],
      ["MOR", "Morelos"],
      ["MEX", "México"],
      ["NAY", "Nayarit"],
      ["NL", "Nuevo León"],
      ["OAX", "Oaxaca"],
      ["PUE", "Puebla"],
      ["QRO", "Querétaro"],
      ["QROO", "Quintana Roo"],
      ["SLP", "San Luis Potosí"],
      ["SIN", "Sinaloa"],
      ["SON", "Sonora"],
      ["TAB", "Tabasco"],
      ["TAMPS", "Tamaulipas"],
      ["TLAX", "Tlaxcala"],
      ["VER", "Veracruz"],
      ["YUC", "Yucatán"],
      ["ZAC", "Zacatecas"],
    ];
    NZ: [
      ["", "Select"],
      ["AUK", "Auckland"],
      ["BOP", "Bay of Plenty"],
      ["CAN", "Canterbury"],
      ["CIT", "Chatham Islands"],
      ["GIS", "Gisborne"],
      ["HKB", "Hawke's Bay"],
      ["MWT", "Manawatu-Wanganui"],
      ["MBH", "Marlborough"],
      ["NSN", "Nelson"],
      ["NTL", "Northland"],
      ["OTA", "Otago"],
      ["STL", "Southland"],
      ["TKI", "Taranaki"],
      ["TAS", "Tasman"],
      ["WKO", "Waikato"],
      ["WGN", "Wellington"],
      ["WTC", "West Coast"],
    ];
    ES: [
      ["", "Select"],
      ["Albacete", "Albacete"],
      ["Alicante", "Alicante"],
      ["Almería", "Almería"],
      ["Asturias", "Asturias"],
      ["Badajoz", "Badajoz"],
      ["Islas Baleares", "Balearic Islands"],
      ["Barcelona", "Barcelona"],
      ["Vizcaya", "Biscay"],
      ["Burgos", "Burgos"],
      ["Cantabria", "Cantabria"],
      ["Castellón", "Castellón"],
      ["Ciudad Real", "Ciudad Real"],
      ["Cuenca", "Cuenca"],
      ["Cáceres", "Cáceres"],
      ["Cádiz", "Cádiz"],
      ["Córdoba", "Córdoba"],
      ["Girona", "Gerona"],
      ["Granada", "Granada"],
      ["Guadalajara", "Guadalajara"],
      ["Guipúzcoa", "Guipúzcoa"],
      ["Huelva", "Huelva"],
      ["Huesca", "Huesca"],
      ["Jaén", "Jaén"],
      ["A Coruña", "La Coruña"],
      ["La Rioja", "La Rioja"],
      ["Las Palmas", "Las Palmas"],
      ["León", "León"],
      ["Lleida", "Lleida"],
      ["Madrid", "Madrid"],
      ["Murcia", "Murcia"],
      ["Málaga", "Málaga"],
      ["Navarra", "Navarra"],
      ["Ourense", "Orense"],
      ["Palencia", "Palencia"],
      ["Pontevedra", "Pontevedra"],
      ["Salamanca", "Salamanca"],
      ["Santa Cruz de Tenerife", "Santa Cruz de Tenerife"],
      ["Segovia", "Segovia"],
      ["Sevilla", "Sevilla"],
      ["Soria", "Soria"],
      ["Tarragona", "Tarragona"],
      ["Teruel", "Teruel"],
      ["Toledo", "Toledo"],
      ["Valencia", "Valencia"],
      ["Valladolid", "Valladolid"],
      ["Zamora", "Zamora"],
      ["Zaragoza", "Zaragoza"],
      ["Álava", "Álava"],
      ["Ávila", "Ávila"],
    ];
    RO: [
      ["", "Select"],
      ["AB", "Alba"],
      ["AR", "Arad"],
      ["AG", "Arges"],
      ["BC", "Bacau"],
      ["BH", "Bihor"],
      ["BN", "Bistrita Nasaud"],
      ["BT", "Botosani"],
      ["BR", "Braila"],
      ["BV", "Brasov"],
      ["B", "Bucharest"],
      ["BZ", "Buzau"],
      ["CL", "Calarasi"],
      ["CS", "Caras Severin"],
      ["CJ", "Cluj"],
      ["CT", "Constanta"],
      ["CV", "Covasna"],
      ["DB", "Dambovita"],
      ["DJ", "Dolj"],
      ["GL", "Galati"],
      ["GR", "Giurgiu"],
      ["GJ", "Gorj"],
      ["HR", "Harghita"],
      ["HD", "Hunedoara"],
      ["IL", "Ialomita"],
      ["IS", "Iasi"],
      ["MM", "Maramures"],
      ["MH", "Mehedinti"],
      ["MS", "Mures"],
      ["NT", "Neamt"],
      ["OT", "Olt"],
      ["PH", "Prahova"],
      ["SJ", "Salaj"],
      ["SM", "Satu Mare"],
      ["SB", "Sibiu"],
      ["SV", "Suceava"],
      ["TR", "Teleorman"],
      ["TM", "Timis"],
      ["VL", "Valcea"],
      ["VS", "Vaslui"],
      ["VN", "Vrancea"],
    ];
  }
}
