name: Revelbeauty - Development deploy
on:
  workflow_dispatch:
    inputs:
      package-version:
        description: 'Version of the static content to deploy'
        required: true

jobs:
  deploy_cdn:
    name: CDN
    uses: trafilea/trafilea-reusable-workflows/.github/workflows/deploy-storefront-static.yaml@feature/cdn-workflows
    with:
      BUILDS_BUCKET: traf-core-builds
      PACKAGE_NAME: storefront-static
      PACKAGE_VERSION: ${{ inputs.package-version }}
      CDN_BUCKET: cdn-dev.revelbeauty.com
      CLOUDFRONT_ID: E22BNUCDZKBQF3
      ENVIRONMENT_ACCOUNT_ID: 571168450468
    secrets: inherit