name: TheSpaDR - All Environments Deploy
on:
  workflow_dispatch:
    inputs:
      package-version:
        description: 'Version of the static content to deploy'
        required: true

jobs:
  deploy_cdn_dev:
    name: CDN-Dev
    uses: trafilea/trafilea-reusable-workflows/.github/workflows/deploy-storefront-static.yaml@feature/cdn-workflows
    with:
      BUILDS_BUCKET: traf-core-builds
      PACKAGE_NAME: storefront-static
      PACKAGE_VERSION: ${{ inputs.package-version }}
      CDN_BUCKET: cdn-dev.thespadr.com
      CLOUDFRONT_ID: E15PBGXLUO0D7A
      ENVIRONMENT_ACCOUNT_ID: 571168450468
    secrets: inherit
  
  deploy_cdn_stage:
    name: CDN-Stage
    uses: trafilea/trafilea-reusable-workflows/.github/workflows/deploy-storefront-static.yaml@feature/cdn-workflows
    with:
      BUILDS_BUCKET: traf-core-builds
      PACKAGE_NAME: storefront-static
      PACKAGE_VERSION: ${{ inputs.package-version }}
      CDN_BUCKET: cdn-stage.thespadr.com
      CLOUDFRONT_ID: E3TL70JJ9MZN9T
      ENVIRONMENT_ACCOUNT_ID: 209977326717
    secrets: inherit
  
  deploy_cdn_prod:
    name: CDN-Prod
    uses: trafilea/trafilea-reusable-workflows/.github/workflows/deploy-storefront-static.yaml@feature/cdn-workflows
    with:
      BUILDS_BUCKET: traf-core-builds
      PACKAGE_NAME: storefront-static
      PACKAGE_VERSION: ${{ inputs.package-version }}
      CDN_BUCKET: cdn.thespadr.com
      CLOUDFRONT_ID: E1S0J140UDVW2G
      ENVIRONMENT_ACCOUNT_ID: 316853325653
    secrets: inherit
