name: Release
on:
  release:
    types: [published]


jobs:
  upload_package:
    name: Build
    uses: trafilea/trafilea-reusable-workflows/.github/workflows/upload-storefront-static.yaml@feature/cdn-workflows
    with:
      BUILDS_BUCKET: traf-core-builds
      PACKAGE_NAME: storefront-static
      PACKAGE_VERSION: ${{ github.ref_name }}
    secrets: inherit